# Generated by Django 2.2.15 on 2020-08-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0017_auto_20200808_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsterinstance',
            name='avg_rune_efficiency',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_accuracy',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_attack',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_crit_damage',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_crit_rate',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_defense',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_hp',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_resistance',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_speed',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_1',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_1_craft',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_1_value',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_2',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_2_craft',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_2_value',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_3',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_3_craft',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_3_value',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_4',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_4_craft',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_4_value',
        ),
        migrations.AddField(
            model_name='runebuild',
            name='artifacts',
            field=models.ManyToManyField(to='herders.ArtifactInstance'),
        ),
    ]
